name: Lint Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint on changed files
        run: |
          git fetch origin main
          git diff --name-only origin/main | grep -E '\.(ts|tsx|js|jsx)$' | xargs npx eslint --max-warnings=0
